"""empty message

Revision ID: 18f207644cb6
Revises: 118238119df2
Create Date: 2019-08-20 21:46:23.070991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f207644cb6'
down_revision = '118238119df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('passwd', sa.String(length=100), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('user', 'passwd')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
